### PR TITLE
Add support for separating media files per chat

### PR DESCRIPTION
**Pull request by mmmeeedddsss**
I have added a flag to create a duplicate of the existing media grouped by chat. 

This was my own need, and saw many people online asking for a similar ability, so I decided to open a PR in here to make that available for public use. 

I have tested the change with my own backup and it is working. If you accept the PR, I'll also open another PR on the wiki section for updating the usage.

Thank you for the great repository!

### CODE REVIEW

**Comment by KnugiHK** [comment]
Hi. Thanks for your contribution first, I will review and test the changes later.

Are there any specific issues opened? If so, please let me know so that I can link the issues to this PR.

**Comment by mmmeeedddsss** [comment]
This was originally my own need, but I can see the following related issue too:
https://github.com/KnugiHK/WhatsApp-Chat-Exporter/issues/88

**Comment by KnugiHK** [comment]
> @KnugiHK Also, should I rebase my commit to dev branch and open the PR from there? Maybe it is better to test once again with my changes on top of dev branch and let you know!

Yes, please.

**Comment by mmmeeedddsss** [comment]
Hey hey !
Thank you @KnugiHK once again for your responsivness. 
I just updated the base branch to dev, merged my changes to dev branch and made the necessary adjustments. It is now running on my local PC with my own android whatsapp db. (mmmeeedddsss:main now contains the KnugiHK:dev + my commit for the feature)

FYI:
- I have mistakenly removed the LICENCE.django file you put
- Incremented the version to 0.10.0. This is a new feature but it is backward compatible so incrementing the minor version seemed ok to me.

**Review by KnugiHK — APPROVED** [review]
I did some changes. Could you please test it again with your database?

**Comment by destaa** [comment]
> I did some changes. Could you please test it again with your database?

is this works with chat group as well?

**Comment by destaa** [comment]
and forgive me, I'm new in github.. as far as I know, KnugiHK has approved mmmeeedddsss's PR, and KnugiHK has commit of the new parser of --create-separated-media.
I thought I can execute the new parser with cloning KnugiHK's dev branch again, with the fresh one. But it isn't working.
What did I miss? should it be merged to dev branch first so I can execute with my database?

**Comment by KnugiHK** [comment]
> > I did some changes. Could you please test it again with your database?
> 
> is this works with chat group as well?

It should works with group chat.

> I thought I can execute the new parser with cloning KnugiHK's dev branch again, with the fresh one. But it isn't working.
>What did I miss? should it be merged to dev branch first so I can execute with my database?

I approved the changes but the commits are not yet being merged.

**Comment by KnugiHK** [comment]
@destaa If you want to try it first, install the exporter with `pip install git+https://github.com/mmmeeedddsss/WhatsApp-Chat-Exporter`.

**Comment by destaa** [comment]
> @destaa If you want to try it first, install the exporter with `pip install git+https://github.com/mmmeeedddsss/WhatsApp-Chat-Exporter`.

nice i'll try..thanks

**Comment by mmmeeedddsss** [comment]
@KnugiHK Sorry for my late response.
Thank you for your review and patches. Also, I'm happy to see your implementation on IOS too!

The current state works well on my local database too. I think it is okay to merge this if you don't have any additional feedback or things to do.

**Comment by KnugiHK** [comment]
> @KnugiHK Sorry for my late response. Thank you for your review and patches. Also, I'm happy to see your implementation on IOS too!
> 
> The current state works well on my local database too. I think it is okay to merge this if you don't have any additional feedback or things to do.

LGTM! Thanks for your contribution again!

**Pull request merged**
